export type ID = string;

/** The recurrence-relevant shape for anything that repeats monthly — currently just
 * the salary, but kept as its own interface so the date math in recurrence.ts stays
 * decoupled from what's being paid. */
export interface RecurringSchedule {
  cycle: 'monthly';
  startDate: string; // ISO date
  lastChargedDate?: string; // ISO date, last cycle boundary already charged
}

/** One recurring monthly paycheck. lastChargedDate is derived from the latest income
 * event tagged with this salary's id, not stored directly on upsert. */
export interface Salary extends RecurringSchedule {
  id: ID;
  amount: number;
}

interface LedgerEventBase {
  id: ID;
  timestamp: string; // ISO datetime
}

export interface IncomeEvent extends LedgerEventBase {
  type: 'income';
  amount: number;
  label: string;
  salaryId?: ID; // set when this payment was auto-generated by the salary simulation
}

export interface ExpenseEvent extends LedgerEventBase {
  type: 'expense';
  amount: number;
  category: string;
  subcategory?: string;
  note?: string;
}

export interface SalaryUpsertEvent extends LedgerEventBase {
  type: 'salary_upsert';
  salary: Salary;
}

export type LedgerEvent = IncomeEvent | ExpenseEvent | SalaryUpsertEvent;

export type LedgerEventType = LedgerEvent['type'];
